# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"   # Maps public port 80 to Nginx port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html5:/var/www/html
    depends_on:
      - server
    develop:
      watch:
        # Action 1: Restart (Configuration Changes)
        # If you edit nginx.conf, restart
        - action: restart
          path: ./nginx/default.conf

    links:
      - server:app.chat.local

#   to work with sqlx do in windows || or use .env
#   $env:DATABASE_URL=<url_here>
  server:
    container_name: chat_server
    build:
      context: .
      # target: final this is for release
      target: dev
    environment:
      - RUST_LOG=chat_server=info
      - DATABASE_URL_NAME=db-url-total
    # volumes for debug
    volumes:
      - .:/app
      - /app/target
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    links:
      - db:app.database.local
    secrets:
      - db-url-total


  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    secrets:
      - db-password
      - db-password-root
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_PASSWORD_FILE=/run/secrets/db-password
      - MARIADB_USER=mariadb
      - MARIADB_DATABASE=chat
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password-root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  mariadb_data:
secrets:
  db-password:
    file: db/password.txt
  db-password-root:
    file: db/password-root.txt
  db-url-total:
    file: db/pass.txt